version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/danmu-desktop"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
