#!/usr/bin/env bash
# setup.sh — Danmu Fire deployment wizard and .env validator
set -euo pipefail

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
_info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
_ok()      { echo -e "${GREEN}[ OK ]${NC}  $*"; }

_WEAK_PASSWORDS="changeme password admin 123456"

_check_weak_password() {
  local val="$1"
  for weak in $_WEAK_PASSWORDS; do
    if [ "$val" = "$weak" ]; then return 0; fi
  done
  return 1
}

# ── Validation (used by both init and check) ─────────────────────────────────

_validate_env() {
  local env_file="${1:-.env}"
  local errors=0
  local warnings=0

  [ -f "$env_file" ] || { _error ".env file not found at $env_file"; exit 1; }

  # shellcheck disable=SC1090
  source "$env_file" 2>/dev/null || true

  # ADMIN_PASSWORD check
  if [ -z "${ADMIN_PASSWORD:-}" ] && [ -z "${ADMIN_PASSWORD_HASHED:-}" ]; then
    _error "ADMIN_PASSWORD or ADMIN_PASSWORD_HASHED must be set"
    errors=$((errors+1))
  elif [ -n "${ADMIN_PASSWORD:-}" ] && _check_weak_password "${ADMIN_PASSWORD}"; then
    _error "ADMIN_PASSWORD is a weak default ('${ADMIN_PASSWORD}'). Set a strong password."
    errors=$((errors+1))
  fi

  # SECRET_KEY in production
  local env_val="${ENV:-production}"
  if [ "$env_val" = "production" ] && [ -z "${SECRET_KEY:-}" ]; then
    _error "SECRET_KEY must be set when ENV=production"
    errors=$((errors+1))
  fi

  # SESSION_COOKIE_SECURE in production
  if [ "$env_val" = "production" ] && [ "${SESSION_COOKIE_SECURE:-true}" = "false" ]; then
    _error "SESSION_COOKIE_SECURE must not be false in production"
    errors=$((errors+1))
  fi

  # CORS wildcard + credentials
  if [ "${CORS_SUPPORTS_CREDENTIALS:-false}" = "true" ] && [ "${CORS_ORIGINS:-*}" = "*" ]; then
    _error "Cannot combine CORS_SUPPORTS_CREDENTIALS=true with CORS_ORIGINS=*"
    errors=$((errors+1))
  fi

  # WS_REQUIRE_TOKEN disabled but token set (likely misconfiguration)
  if [ "${WS_REQUIRE_TOKEN:-false}" = "false" ] && [ -n "${WS_AUTH_TOKEN:-}" ]; then
    _warn "WS_AUTH_TOKEN is set but WS_REQUIRE_TOKEN=false — token will not be enforced"
    warnings=$((warnings+1))
  fi

  # Traefik profile: check DOMAIN
  if [ "${_PROFILE:-}" = "traefik" ] && [ -z "${DOMAIN:-}" ]; then
    _error "DOMAIN must be set when using the traefik profile"
    errors=$((errors+1))
  fi

  if [ $errors -gt 0 ]; then
    echo ""
    _error "$errors error(s) found. Fix them before starting."
    exit 1
  elif [ $warnings -gt 0 ]; then
    echo ""
    _warn "$warnings warning(s). Review before deploying to production."
  else
    _ok "Configuration looks good."
  fi
}

# ── Interactive init ──────────────────────────────────────────────────────────

_init() {
  echo ""
  echo -e "${CYAN}=== Danmu Fire Setup ===${NC}"
  echo ""

  # Mode selection
  echo "Select deployment mode:"
  echo "  1) Local HTTP (dev/testing, no HTTPS)"
  echo "  2) HTTPS with self-signed certificate (LAN / VPS, no domain required)"
  echo "  3) Traefik + Let's Encrypt (requires public domain)"
  echo ""
  read -rp "Mode [1/2/3]: " mode
  case "$mode" in
    1) _PROFILE="http" ;;
    2) _PROFILE="https" ;;
    3) _PROFILE="traefik" ;;
    *) _error "Invalid choice"; exit 1 ;;
  esac

  # Redis
  read -rp "Add Redis rate limiting? [y/N]: " use_redis
  local redis_profile=""
  if [ "${use_redis,,}" = "y" ]; then
    redis_profile=" --profile redis"
    _REDIS=true
  fi

  # Admin password
  echo ""
  while true; do
    read -rsp "Set ADMIN_PASSWORD: " admin_pass
    echo ""
    if [ -z "$admin_pass" ]; then
      _error "Password cannot be empty"; continue
    fi
    if _check_weak_password "$admin_pass"; then
      _error "Password is too weak. Choose something stronger."; continue
    fi
    break
  done

  # Traefik extras
  local domain="" acme_email=""
  if [ "$_PROFILE" = "traefik" ]; then
    read -rp "Domain (e.g. danmu.example.com): " domain
    [ -z "$domain" ] && { _error "Domain is required for traefik mode"; exit 1; }
    read -rp "ACME email (for Let's Encrypt): " acme_email
    [ -z "$acme_email" ] && { _error "ACME_EMAIL is required for traefik mode"; exit 1; }
  fi

  # HTTPS extras
  local server_ip="" server_domain=""
  if [ "$_PROFILE" = "https" ]; then
    read -rp "Public IP (optional, for SAN — leave blank for localhost only): " server_ip
    read -rp "Domain (optional, for SAN — leave blank for localhost only): " server_domain
  fi

  # Write .env
  local env_file=".env"
  if [ -f "$env_file" ]; then
    read -rp ".env already exists. Overwrite? [y/N]: " overwrite
    [ "${overwrite,,}" != "y" ] && { _info "Cancelled. Existing .env unchanged."; exit 0; }
  fi

  cat > "$env_file" <<EOF
# Generated by setup.sh — $(date)
ADMIN_PASSWORD=${admin_pass}
SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null || openssl rand -hex 32)
ENV=production
PORT=4000
WS_PORT=4001
SESSION_COOKIE_SECURE=true
SESSION_COOKIE_SAMESITE=Strict
TRUSTED_HOSTS=localhost,127.0.0.1${domain:+,$domain}
WS_REQUIRE_TOKEN=false
WS_AUTH_TOKEN=
RATE_LIMIT_BACKEND=${_REDIS:+redis}${_REDIS:-memory}
REDIS_PASSWORD=changeme
EOF

  [ -n "$domain" ]        && echo "DOMAIN=${domain}" >> "$env_file"
  [ -n "$acme_email" ]    && echo "ACME_EMAIL=${acme_email}" >> "$env_file"
  [ -n "$server_ip" ]     && echo "SERVER_IP=${server_ip}" >> "$env_file"
  [ -n "$server_domain" ] && echo "SERVER_DOMAIN=${server_domain}" >> "$env_file"
  [ "${_REDIS:-}" = "true" ] && echo "REDIS_URL=redis://:changeme@redis:6379/0" >> "$env_file"

  echo ""
  _ok ".env written."

  # Traefik acme.json
  if [ "$_PROFILE" = "traefik" ]; then
    mkdir -p traefik
    touch traefik/acme.json && chmod 600 traefik/acme.json
    _ok "traefik/acme.json created."
  fi

  echo ""
  _info "To start Danmu Fire, run:"
  echo ""
  echo "    docker compose --profile ${_PROFILE}${redis_profile} up -d"
  echo ""
  _warn "Change REDIS_PASSWORD in .env before production use."
}

# ── Entry point ───────────────────────────────────────────────────────────────

case "${1:-}" in
  init)  _init ;;
  check) _PROFILE="${2:-}" _validate_env "${3:-.env}" ;;
  *)
    echo "Usage:"
    echo "  ./setup.sh init              Interactive wizard → writes .env"
    echo "  ./setup.sh check [profile]   Validate existing .env"
    exit 1
    ;;
esac
