// AUTO-GENERATED — do NOT edit this file directly.
// Edit files in locales/{lang}/translation.json, then run:
//   npm run build:i18n   (from danmu-desktop/)

/* eslint-disable */

const SUPPORTED = ["en", "zh", "ja", "ko"];

const _resources = {
    "en": {
      "skipToMainContent": "Skip to main content",
      "title": "Danmu Fire",
      "subtitle": "Configure and launch the danmu overlay",
      "hostLabel": "Server Address (IP or Domain)",
      "hostPlaceholder": "e.g., 127.0.0.1 or mydomain.com",
      "portLabel": "WebSocket Port",
      "portPlaceholder": "e.g., 4001",
      "displayLabel": "Target Display",
      "syncMultiDisplay": "Enable synchronous multi-display",
      "startButton": "Start Danmu",
      "stopButton": "Stop Danmu",
      "statusConnecting": "Connecting to server...",
      "statusConnected": "Connected to server",
      "statusDisconnected": "Connection lost, reconnecting...",
      "statusIdle": "Disconnected",
      "statusStopped": "Stopped",
      "statusConnectionFailed": "Connection failed",
      "toastStarting": "Starting danmu overlay connection...",
      "toastConnected": "Successfully connected to server",
      "toastReconnecting": "Connection lost, attempting to reconnect...",
      "toastStopped": "Danmu overlay stopped",
      "toastSettingsLoaded": "Previous settings loaded",
      "toastConnectionFailed": "Unable to reach the server. Please verify settings.",
      "errorEmptyHost": "Please enter a server address",
      "errorInvalidHost": "Invalid server address. Please enter a valid IP or domain",
      "errorEmptyPort": "Please enter a port number",
      "errorInvalidPort": "Invalid port. Please enter a number between 1 and 65535",
      "exportSettings": "Export Settings",
      "importSettings": "Import Settings",
      "updateKicker": "UPDATE",
      "updateAvailableShort": "UPDATE",
      "updateAvailableTitle": "New version available",
      "updateReadyTitle": "Update ready to install",
      "updateChecking": "Checking for updates…",
      "updateCheckFailed": "Update check failed",
      "updateCheckFailedShort": "CHECK FAILED",
      "updateUpToDate": "You're up to date",
      "updateUpToDateShort": "UP TO DATE",
      "updateRestartToInstall": "RESTART TO INSTALL",
      "updateDownloadComplete": "Download complete",
      "updateDownloadedToast": "Update downloaded — restart to install",
      "updateInstallNow": "Restart to install",
      "updateRemindLater": "Remind me later",
      "updateSkipVersion": "Skip this version"
    },
    "zh": {
      "skipToMainContent": "跳至主要內容",
      "title": "Danmu Fire",
      "subtitle": "配置並啟動彈幕",
      "hostLabel": "伺服器位址（IP 或網域）",
      "hostPlaceholder": "例如：127.0.0.1 或 mydomain.com",
      "portLabel": "WebSocket 連接埠",
      "portPlaceholder": "例如：4001",
      "displayLabel": "目標顯示器",
      "syncMultiDisplay": "啟用同步多顯示器",
      "startButton": "啟動彈幕",
      "stopButton": "關閉彈幕",
      "statusConnecting": "正在連線至伺服器...",
      "statusConnected": "已連線至伺服器",
      "statusDisconnected": "連線中斷，重新連線中...",
      "statusIdle": "已中斷連線",
      "statusStopped": "已停止",
      "statusConnectionFailed": "連線失敗",
      "toastStarting": "正在啟動彈幕連線...",
      "toastConnected": "成功連線至伺服器",
      "toastReconnecting": "連線中斷，正在嘗試重新連線...",
      "toastStopped": "彈幕已停止",
      "toastSettingsLoaded": "已載入先前的設定",
      "toastConnectionFailed": "無法連線至伺服器，請檢查設定",
      "errorEmptyHost": "請輸入伺服器位址",
      "errorInvalidHost": "無效的伺服器位址。請輸入有效的 IP 或網域",
      "errorEmptyPort": "請輸入連接埠號碼",
      "errorInvalidPort": "無效的連接埠。請輸入 1 到 65535 之間的數字",
      "exportSettings": "匯出設定",
      "importSettings": "匯入設定",
      "updateKicker": "更新",
      "updateAvailableShort": "可更新",
      "updateAvailableTitle": "有新版本可用",
      "updateReadyTitle": "更新已準備就緒",
      "updateChecking": "正在檢查更新…",
      "updateCheckFailed": "檢查更新失敗",
      "updateCheckFailedShort": "檢查失敗",
      "updateUpToDate": "已是最新版本",
      "updateUpToDateShort": "已是最新",
      "updateRestartToInstall": "重啟以安裝",
      "updateDownloadComplete": "下載完成",
      "updateDownloadedToast": "更新已下載完成，重啟即可安裝",
      "updateInstallNow": "重啟並安裝",
      "updateRemindLater": "稍後提醒",
      "updateSkipVersion": "略過此版本"
    },
    "ja": {
      "skipToMainContent": "メインコンテンツへスキップ",
      "title": "Danmu Fire",
      "subtitle": "オーバーレイの設定と起動",
      "hostLabel": "サーバーアドレス（IPまたはドメイン）",
      "hostPlaceholder": "例：127.0.0.1 または mydomain.com",
      "portLabel": "WebSocketポート",
      "portPlaceholder": "例：4001",
      "displayLabel": "対象ディスプレイ",
      "syncMultiDisplay": "同期マルチディスプレイを有効化",
      "startButton": "オーバーレイ開始",
      "stopButton": "オーバーレイ停止",
      "statusConnecting": "サーバーに接続中...",
      "statusConnected": "サーバーに接続しました",
      "statusDisconnected": "接続が切断されました。再接続中...",
      "statusIdle": "切断済み",
      "statusStopped": "停止済み",
      "statusConnectionFailed": "接続に失敗しました",
      "toastStarting": "弾幕オーバーレイ接続を開始しています...",
      "toastConnected": "サーバーに接続しました",
      "toastReconnecting": "接続が切断されました。再接続を試みています...",
      "toastStopped": "弾幕オーバーレイを停止しました",
      "toastSettingsLoaded": "以前の設定を読み込みました",
      "toastConnectionFailed": "サーバーに接続できません。設定を確認してください。",
      "errorEmptyHost": "サーバーアドレスを入力してください",
      "errorInvalidHost": "無効なサーバーアドレスです。有効なIPまたはドメインを入力してください",
      "errorEmptyPort": "ポート番号を入力してください",
      "errorInvalidPort": "無効なポートです。1から65535の数字を入力してください",
      "exportSettings": "設定をエクスポート",
      "importSettings": "設定をインポート",
      "updateKicker": "更新",
      "updateAvailableShort": "更新あり",
      "updateAvailableTitle": "新しいバージョンが利用可能です",
      "updateReadyTitle": "更新の準備ができました",
      "updateChecking": "更新を確認中…",
      "updateCheckFailed": "更新の確認に失敗しました",
      "updateCheckFailedShort": "確認失敗",
      "updateUpToDate": "最新版です",
      "updateUpToDateShort": "最新版",
      "updateRestartToInstall": "再起動でインストール",
      "updateDownloadComplete": "ダウンロード完了",
      "updateDownloadedToast": "更新をダウンロードしました — 再起動でインストール",
      "updateInstallNow": "再起動してインストール",
      "updateRemindLater": "後で通知",
      "updateSkipVersion": "このバージョンをスキップ"
    },
    "ko": {
      "skipToMainContent": "본문으로 건너뛰기",
      "title": "Danmu Fire",
      "subtitle": "오버레이 구성 및 실행",
      "hostLabel": "서버 주소 (IP 또는 도메인)",
      "hostPlaceholder": "예: 127.0.0.1 또는 mydomain.com",
      "portLabel": "WebSocket 포트",
      "portPlaceholder": "예: 4001",
      "displayLabel": "대상 디스플레이",
      "syncMultiDisplay": "동기 멀티 디스플레이 활성화",
      "startButton": "오버레이 시작",
      "stopButton": "오버레이 중지",
      "statusConnecting": "서버에 연결 중...",
      "statusConnected": "서버에 연결됨",
      "statusDisconnected": "연결이 끊어졌습니다. 재연결 중...",
      "statusIdle": "연결 해제됨",
      "statusStopped": "중지됨",
      "statusConnectionFailed": "연결 실패",
      "toastStarting": "탄막 오버레이 연결을 시작하는 중...",
      "toastConnected": "서버에 성공적으로 연결되었습니다",
      "toastReconnecting": "연결이 끊어졌습니다. 재연결을 시도하는 중...",
      "toastStopped": "탄막 오버레이가 중지되었습니다",
      "toastSettingsLoaded": "이전 설정을 불러왔습니다",
      "toastConnectionFailed": "서버에 연결할 수 없습니다. 설정을 확인해 주세요.",
      "errorEmptyHost": "서버 주소를 입력해 주세요",
      "errorInvalidHost": "잘못된 서버 주소입니다. 유효한 IP 또는 도메인을 입력해 주세요",
      "errorEmptyPort": "포트 번호를 입력해 주세요",
      "errorInvalidPort": "잘못된 포트입니다. 1에서 65535 사이의 숫자를 입력해 주세요",
      "exportSettings": "설정 내보내기",
      "importSettings": "설정 가져오기",
      "updateKicker": "업데이트",
      "updateAvailableShort": "업데이트",
      "updateAvailableTitle": "새 버전이 있습니다",
      "updateReadyTitle": "업데이트 설치 준비 완료",
      "updateChecking": "업데이트 확인 중…",
      "updateCheckFailed": "업데이트 확인 실패",
      "updateCheckFailedShort": "확인 실패",
      "updateUpToDate": "최신 버전입니다",
      "updateUpToDateShort": "최신",
      "updateRestartToInstall": "재시작하여 설치",
      "updateDownloadComplete": "다운로드 완료",
      "updateDownloadedToast": "업데이트가 다운로드되었습니다 — 재시작하여 설치하세요",
      "updateInstallNow": "재시작하여 설치",
      "updateRemindLater": "나중에 알림",
      "updateSkipVersion": "이 버전 건너뛰기"
    }
  };

const i18n = {
  currentLang: "en",

  // Exposed for backward-compatibility with tests that inspect translations directly
  translations: _resources,

  /** Translate a key with optional {var} interpolation.
   *  Respects this.currentLang so tests can do: i18n.currentLang = "zh"
   *  without needing to call setLanguage().
   *
   *  Returns the key itself when:
   *  - currentLang is not a supported locale
   *  - the key does not exist in the locale
   */
  t(key, vars) {
    if (!SUPPORTED.includes(this.currentLang)) return key;
    const dict = _resources[this.currentLang];
    if (!dict) return key;
    let text = dict[key];
    if (text === undefined) return key;
    if (vars) {
      Object.keys(vars).forEach((k) => {
        text = text.replace(new RegExp("\\{" + k + "\\}", "g"), vars[k]);
      });
    }
    return text;
  },

  setLanguage(lang) {
    if (!SUPPORTED.includes(lang)) return;
    this.currentLang = lang;
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("danmu-lang", lang);
    }
    // Update <html lang=""> so CSS :lang() picks the right CJK font
    if (typeof document !== "undefined" && document.documentElement) {
      document.documentElement.lang = lang;
    }
    this.updateUI();
  },

  /** Detect and apply the correct language (async — uses Electron IPC if available). */
  async loadLanguage() {
    const saved =
      typeof localStorage !== "undefined" && localStorage.getItem("danmu-lang");
    if (saved && SUPPORTED.includes(saved)) {
      this.currentLang = saved;
      return;
    }

    // Try Electron system locale first
    try {
      if (
        typeof window !== "undefined" &&
        window.API &&
        typeof window.API.getSystemLocale === "function"
      ) {
        const systemLocale = await window.API.getSystemLocale();
        console.log("[i18n] System locale:", systemLocale);
        const detected = this._detectLangFromLocale(systemLocale);
        if (detected) {
          this.currentLang = detected;
          return;
        }
      }
    } catch (err) {
      console.warn("[i18n] getSystemLocale failed, falling back:", err);
    }

    // Browser fallback
    const browserLang =
      typeof navigator !== "undefined"
        ? navigator.language || navigator.userLanguage
        : "";
    console.log("[i18n] Browser language:", browserLang);
    const detected = this._detectLangFromLocale(browserLang);
    if (detected) this.currentLang = detected;
  },

  _detectLangFromLocale(locale) {
    if (!locale) return null;
    if (locale.startsWith("zh")) return "zh";
    if (locale.startsWith("ja")) return "ja";
    if (locale.startsWith("ko")) return "ko";
    return null;
  },

  updateUI() {
    if (typeof document === "undefined") return;
    // Keep <html lang=""> in sync so CSS :lang() picks the right CJK font
    if (document.documentElement) {
      document.documentElement.lang = this.currentLang;
    }
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const text = this.t(key);
      if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
        el.placeholder = text;
      } else {
        el.textContent = text;
      }
    });
    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      const key = el.getAttribute("data-i18n-placeholder");
      el.placeholder = this.t(key);
    });
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = i18n;
}
