// AUTO-GENERATED — do NOT edit this file directly.
// Edit files in locales/{lang}/translation.json, then run:
//   npm run build:i18n   (from danmu-desktop/)

/* eslint-disable */

const SUPPORTED = ["en", "zh", "ja", "ko"];

const _resources = {
    "en": {
      "skipToMainContent": "Skip to main content",
      "title": "Danmu Fire",
      "subtitle": "Configure and launch the danmu overlay",
      "hostLabel": "Server Address (IP or Domain)",
      "hostPlaceholder": "e.g., 127.0.0.1 or mydomain.com",
      "portLabel": "WebSocket Port",
      "portPlaceholder": "e.g., 4001",
      "displayLabel": "Target Display",
      "syncMultiDisplay": "Enable synchronous multi-display",
      "startButton": "Start Danmu",
      "stopButton": "Stop Danmu",
      "statusConnecting": "Connecting to server...",
      "statusConnected": "Connected to server",
      "statusDisconnected": "Connection lost, reconnecting...",
      "statusIdle": "Disconnected",
      "statusStopped": "Stopped",
      "statusConnectionFailed": "Connection failed",
      "toastStarting": "Starting danmu overlay connection...",
      "toastConnected": "Successfully connected to server",
      "toastReconnecting": "Connection lost, attempting to reconnect...",
      "toastStopped": "Danmu overlay stopped",
      "toastSettingsLoaded": "Previous settings loaded",
      "toastConnectionFailed": "Unable to reach the server. Please verify settings.",
      "errorEmptyHost": "Please enter a server address",
      "errorInvalidHost": "Invalid server address. Please enter a valid IP or domain",
      "errorEmptyPort": "Please enter a port number",
      "errorInvalidPort": "Invalid port. Please enter a number between 1 and 65535",
      "exportSettings": "Export Settings",
      "importSettings": "Import Settings",
      "updateKicker": "UPDATE",
      "updateAvailableShort": "UPDATE",
      "updateAvailableTitle": "New version available",
      "updateReadyTitle": "Update ready to install",
      "updateChecking": "Checking for updates…",
      "updateCheckFailed": "Update check failed",
      "updateCheckFailedShort": "CHECK FAILED",
      "updateUpToDate": "You're up to date",
      "updateUpToDateShort": "UP TO DATE",
      "updateRestartToInstall": "RESTART TO INSTALL",
      "updateDownloadComplete": "Download complete",
      "updateDownloadedToast": "Update downloaded — restart to install",
      "updateInstallNow": "Restart to install",
      "updateRemindLater": "Remind me later",
      "updateSkipVersion": "Skip this version",
      "updateSectionTitle": "Updates",
      "updateSectionKicker": "UPDATES",
      "updateCheckNow": "Check now",
      "updatePrefsKicker": "UPDATE BEHAVIOR",
      "updatePrefAutoDownload": "Auto-download updates",
      "updatePrefAutoDownloadHint": "Background download · applies on next launch",
      "updatePrefBetaChannel": "Join beta channel",
      "updatePrefBetaChannelHint": "Try features early · may be unstable",
      "updateChangelogKicker": "RECENT CHANGES",
      "updateChangelogFullLink": "Full changelog →",
      "updateChangelogEmpty": "No changelog data yet",
      "connSectionTitle": "Connection Status",
      "connSectionKicker": "CONNECTION",
      "firstrunLead": "Connect to your danmu server",
      "firstrunHint": "First launch needs the server address · saved for auto-reconnect next time",
      "firstrunStepServer": "SERVER",
      "firstrunStepTest": "TEST",
      "firstrunStepReady": "READY",
      "firstrunFieldLabel": "SERVER · IP / HOST",
      "firstrunFieldHelp": "Uses wss://HOST:PORT/ws · default WebSocket port 4001",
      "firstrunTestBtn": "Test connection",
      "firstrunRecentLabel": "RECENT",
      "firstrunRemember": "Remember this server (auto-connect next time)",
      "firstrunRememberHint": "Stored in localStorage · resettable from ⚙ Connection → Reset",
      "firstrunDocsLink": "Deployment docs →",
      "firstrunSkip": "Set up later",
      "firstrunConfirm": "Connect and start receiving →",
      "overlaySectionTitle": "Overlay",
      "overlaySectionKicker": "DISPLAY",
      "overlayCardTitle": "Show danmu overlay",
      "overlayCardHint": "Shortcut: ⌘⇧D",
      "overlayButtonStart": "▶ Open overlay",
      "overlayButtonStop": "■ Close overlay",
      "overlayActionClear": "⌫ Clear screen",
      "overlayNoteKicker": "NOTE",
      "overlayNoteBody": "Font, color, size, opacity, speed, layout, and effects of each danmu are parameters the audience attaches when sending — not configured here. This window only controls whether the overlay is shown, which display it lives on, and the server connection.",
      "sectionKeysTitle": "Shortcuts",
      "sectionKeysKicker": "SHORTCUTS",
      "sectionAboutTitle": "About",
      "sectionAboutKicker": "ABOUT",
      "clientNavConn": "Connection",
      "clientNavOverlay": "Overlay",
      "clientNavKeys": "Shortcuts",
      "clientNavUpdate": "Updates",
      "clientNavAbout": "About",
      "connStatLatency": "Latency",
      "connStatReconnect": "Reconnects",
      "connStatReconnectUnit": "",
      "connStatUptime": "Uptime",
      "connBtnReconnect": "Reconnect",
      "connBtnEdit": "Edit",
      "connBtnClose": "Close",
      "connFlowKicker": "MESSAGE FLOW · last 30s",
      "connFlowRx": "RX",
      "connFlowRate": "RATE",
      "connFlowPeak": "PEAK",
      "connEditKicker": "CONNECTION · EDIT",
      "overlayDisplayLabel": "Display on",
      "overlayScreenDetecting": "DISPLAY · detecting…",
      "overlayScreenCount": "DISPLAY · {count} screen(s) detected"
    },
    "zh": {
      "skipToMainContent": "跳至主要內容",
      "title": "Danmu Fire",
      "subtitle": "配置並啟動彈幕",
      "hostLabel": "伺服器位址（IP 或網域）",
      "hostPlaceholder": "例如：127.0.0.1 或 mydomain.com",
      "portLabel": "WebSocket 連接埠",
      "portPlaceholder": "例如：4001",
      "displayLabel": "目標顯示器",
      "syncMultiDisplay": "啟用同步多顯示器",
      "startButton": "啟動彈幕",
      "stopButton": "關閉彈幕",
      "statusConnecting": "正在連線至伺服器...",
      "statusConnected": "已連線至伺服器",
      "statusDisconnected": "連線中斷，重新連線中...",
      "statusIdle": "已中斷連線",
      "statusStopped": "已停止",
      "statusConnectionFailed": "連線失敗",
      "toastStarting": "正在啟動彈幕連線...",
      "toastConnected": "成功連線至伺服器",
      "toastReconnecting": "連線中斷，正在嘗試重新連線...",
      "toastStopped": "彈幕已停止",
      "toastSettingsLoaded": "已載入先前的設定",
      "toastConnectionFailed": "無法連線至伺服器，請檢查設定",
      "errorEmptyHost": "請輸入伺服器位址",
      "errorInvalidHost": "無效的伺服器位址。請輸入有效的 IP 或網域",
      "errorEmptyPort": "請輸入連接埠號碼",
      "errorInvalidPort": "無效的連接埠。請輸入 1 到 65535 之間的數字",
      "exportSettings": "匯出設定",
      "importSettings": "匯入設定",
      "updateKicker": "更新",
      "updateAvailableShort": "可更新",
      "updateAvailableTitle": "有新版本可用",
      "updateReadyTitle": "更新已準備就緒",
      "updateChecking": "正在檢查更新…",
      "updateCheckFailed": "檢查更新失敗",
      "updateCheckFailedShort": "檢查失敗",
      "updateUpToDate": "已是最新版本",
      "updateUpToDateShort": "已是最新",
      "updateRestartToInstall": "重啟以安裝",
      "updateDownloadComplete": "下載完成",
      "updateDownloadedToast": "更新已下載完成，重啟即可安裝",
      "updateInstallNow": "重啟並安裝",
      "updateRemindLater": "稍後提醒",
      "updateSkipVersion": "略過此版本",
      "updateSectionTitle": "更新",
      "updateSectionKicker": "UPDATES",
      "updateCheckNow": "立即檢查",
      "updatePrefsKicker": "UPDATE BEHAVIOR",
      "updatePrefAutoDownload": "自動下載更新",
      "updatePrefAutoDownloadHint": "背景下載 · 下次啟動套用",
      "updatePrefBetaChannel": "加入測試版通道",
      "updatePrefBetaChannelHint": "搶先測試新功能 · 可能不穩",
      "updateChangelogKicker": "RECENT CHANGES",
      "updateChangelogFullLink": "完整 changelog →",
      "updateChangelogEmpty": "尚未取得 changelog 資料",
      "connSectionTitle": "連線狀態",
      "connSectionKicker": "CONNECTION",
      "firstrunLead": "連到你的彈幕伺服器",
      "firstrunHint": "首次啟動需要設定伺服器位址 · 設定後會記住，下次自動重連",
      "firstrunStepServer": "SERVER",
      "firstrunStepTest": "TEST",
      "firstrunStepReady": "READY",
      "firstrunFieldLabel": "SERVER · IP / HOST",
      "firstrunFieldHelp": "使用 wss://HOST:PORT/ws · 預設 WebSocket port 4001",
      "firstrunTestBtn": "測試連線",
      "firstrunRecentLabel": "RECENT",
      "firstrunRemember": "記住這個伺服器（下次自動連線）",
      "firstrunRememberHint": "設定存於 localStorage · 可從 ⚙ 連線 → 重新設定 重置",
      "firstrunDocsLink": "部署文件 →",
      "firstrunSkip": "稍後設定",
      "firstrunConfirm": "連線並開始接收 →",
      "overlaySectionTitle": "Overlay",
      "overlaySectionKicker": "DISPLAY",
      "overlayCardTitle": "顯示彈幕 Overlay",
      "overlayCardHint": "快捷鍵: ⌘⇧D",
      "overlayButtonStart": "▶ 開啟 Overlay",
      "overlayButtonStop": "■ 關閉 Overlay",
      "overlayActionClear": "⌫ 清空畫面",
      "overlayNoteKicker": "NOTE",
      "overlayNoteBody": "彈幕的字體、顏色、大小、透明度、速度、排版與效果為觀眾每次發送時帶上的參數,不在此視窗控制。此視窗僅決定 overlay 是否顯示、顯示於哪個螢幕,以及與 server 的連線。",
      "sectionKeysTitle": "快捷鍵",
      "sectionKeysKicker": "SHORTCUTS",
      "sectionAboutTitle": "關於",
      "sectionAboutKicker": "ABOUT",
      "clientNavConn": "連線",
      "clientNavOverlay": "Overlay",
      "clientNavKeys": "快捷鍵",
      "clientNavUpdate": "更新",
      "clientNavAbout": "關於",
      "connStatLatency": "延遲",
      "connStatReconnect": "重連",
      "connStatReconnectUnit": "次",
      "connStatUptime": "上線",
      "connBtnReconnect": "重連",
      "connBtnEdit": "更改",
      "connBtnClose": "關閉",
      "connFlowKicker": "MESSAGE FLOW · 最近 30 秒",
      "connFlowRx": "RX",
      "connFlowRate": "RATE",
      "connFlowPeak": "PEAK",
      "connEditKicker": "CONNECTION · EDIT",
      "overlayDisplayLabel": "顯示於",
      "overlayScreenDetecting": "DISPLAY · 偵測中…",
      "overlayScreenCount": "DISPLAY · 偵測到 {count} 個螢幕"
    },
    "ja": {
      "skipToMainContent": "メインコンテンツへスキップ",
      "title": "Danmu Fire",
      "subtitle": "オーバーレイの設定と起動",
      "hostLabel": "サーバーアドレス（IPまたはドメイン）",
      "hostPlaceholder": "例：127.0.0.1 または mydomain.com",
      "portLabel": "WebSocketポート",
      "portPlaceholder": "例：4001",
      "displayLabel": "対象ディスプレイ",
      "syncMultiDisplay": "同期マルチディスプレイを有効化",
      "startButton": "オーバーレイ開始",
      "stopButton": "オーバーレイ停止",
      "statusConnecting": "サーバーに接続中...",
      "statusConnected": "サーバーに接続しました",
      "statusDisconnected": "接続が切断されました。再接続中...",
      "statusIdle": "切断済み",
      "statusStopped": "停止済み",
      "statusConnectionFailed": "接続に失敗しました",
      "toastStarting": "弾幕オーバーレイ接続を開始しています...",
      "toastConnected": "サーバーに接続しました",
      "toastReconnecting": "接続が切断されました。再接続を試みています...",
      "toastStopped": "弾幕オーバーレイを停止しました",
      "toastSettingsLoaded": "以前の設定を読み込みました",
      "toastConnectionFailed": "サーバーに接続できません。設定を確認してください。",
      "errorEmptyHost": "サーバーアドレスを入力してください",
      "errorInvalidHost": "無効なサーバーアドレスです。有効なIPまたはドメインを入力してください",
      "errorEmptyPort": "ポート番号を入力してください",
      "errorInvalidPort": "無効なポートです。1から65535の数字を入力してください",
      "exportSettings": "設定をエクスポート",
      "importSettings": "設定をインポート",
      "updateKicker": "更新",
      "updateAvailableShort": "更新あり",
      "updateAvailableTitle": "新しいバージョンが利用可能です",
      "updateReadyTitle": "更新の準備ができました",
      "updateChecking": "更新を確認中…",
      "updateCheckFailed": "更新の確認に失敗しました",
      "updateCheckFailedShort": "確認失敗",
      "updateUpToDate": "最新版です",
      "updateUpToDateShort": "最新版",
      "updateRestartToInstall": "再起動でインストール",
      "updateDownloadComplete": "ダウンロード完了",
      "updateDownloadedToast": "更新をダウンロードしました — 再起動でインストール",
      "updateInstallNow": "再起動してインストール",
      "updateRemindLater": "後で通知",
      "updateSkipVersion": "このバージョンをスキップ",
      "updateSectionTitle": "アップデート",
      "updateSectionKicker": "UPDATES",
      "updateCheckNow": "今すぐ確認",
      "updatePrefsKicker": "UPDATE BEHAVIOR",
      "updatePrefAutoDownload": "更新を自動ダウンロード",
      "updatePrefAutoDownloadHint": "バックグラウンドDL · 次回起動時に適用",
      "updatePrefBetaChannel": "ベータチャネルに参加",
      "updatePrefBetaChannelHint": "新機能を先行体験 · 不安定の可能性あり",
      "updateChangelogKicker": "RECENT CHANGES",
      "updateChangelogFullLink": "完全な changelog →",
      "updateChangelogEmpty": "changelog データがまだありません",
      "connSectionTitle": "接続状態",
      "connSectionKicker": "CONNECTION",
      "firstrunLead": "弾幕サーバーに接続",
      "firstrunHint": "初回起動はサーバーアドレス設定が必要 · 設定後は次回自動再接続",
      "firstrunStepServer": "SERVER",
      "firstrunStepTest": "TEST",
      "firstrunStepReady": "READY",
      "firstrunFieldLabel": "SERVER · IP / HOST",
      "firstrunFieldHelp": "wss://HOST:PORT/ws を使用 · 既定 WebSocket port 4001",
      "firstrunTestBtn": "接続テスト",
      "firstrunRecentLabel": "RECENT",
      "firstrunRemember": "このサーバーを記憶 (次回自動接続)",
      "firstrunRememberHint": "localStorage に保存 · ⚙ 接続 → リセットで解除可能",
      "firstrunDocsLink": "デプロイ手順 →",
      "firstrunSkip": "後で設定",
      "firstrunConfirm": "接続して受信開始 →",
      "overlaySectionTitle": "Overlay",
      "overlaySectionKicker": "DISPLAY",
      "overlayCardTitle": "弾幕オーバーレイを表示",
      "overlayCardHint": "ショートカット: ⌘⇧D",
      "overlayButtonStart": "▶ Overlay を開く",
      "overlayButtonStop": "■ Overlay を閉じる",
      "overlayActionClear": "⌫ 画面クリア",
      "overlayNoteKicker": "NOTE",
      "overlayNoteBody": "弾幕のフォント・色・サイズ・透明度・速度・レイアウト・エフェクトは観客が送信時に付与するパラメータで、このウィンドウでは設定しません。ここで決めるのは overlay の表示有無・表示先ディスプレイ・サーバー接続だけです。",
      "sectionKeysTitle": "ショートカット",
      "sectionKeysKicker": "SHORTCUTS",
      "sectionAboutTitle": "アバウト",
      "sectionAboutKicker": "ABOUT",
      "clientNavConn": "接続",
      "clientNavOverlay": "オーバーレイ",
      "clientNavKeys": "ショートカット",
      "clientNavUpdate": "アップデート",
      "clientNavAbout": "アバウト",
      "connStatLatency": "遅延",
      "connStatReconnect": "再接続",
      "connStatReconnectUnit": "回",
      "connStatUptime": "稼働",
      "connBtnReconnect": "再接続",
      "connBtnEdit": "変更",
      "connBtnClose": "閉じる",
      "connFlowKicker": "MESSAGE FLOW · 直近 30 秒",
      "connFlowRx": "RX",
      "connFlowRate": "RATE",
      "connFlowPeak": "PEAK",
      "connEditKicker": "CONNECTION · EDIT",
      "overlayDisplayLabel": "表示先",
      "overlayScreenDetecting": "DISPLAY · 検出中…",
      "overlayScreenCount": "DISPLAY · {count} 画面検出"
    },
    "ko": {
      "skipToMainContent": "본문으로 건너뛰기",
      "title": "Danmu Fire",
      "subtitle": "오버레이 구성 및 실행",
      "hostLabel": "서버 주소 (IP 또는 도메인)",
      "hostPlaceholder": "예: 127.0.0.1 또는 mydomain.com",
      "portLabel": "WebSocket 포트",
      "portPlaceholder": "예: 4001",
      "displayLabel": "대상 디스플레이",
      "syncMultiDisplay": "동기 멀티 디스플레이 활성화",
      "startButton": "오버레이 시작",
      "stopButton": "오버레이 중지",
      "statusConnecting": "서버에 연결 중...",
      "statusConnected": "서버에 연결됨",
      "statusDisconnected": "연결이 끊어졌습니다. 재연결 중...",
      "statusIdle": "연결 해제됨",
      "statusStopped": "중지됨",
      "statusConnectionFailed": "연결 실패",
      "toastStarting": "탄막 오버레이 연결을 시작하는 중...",
      "toastConnected": "서버에 성공적으로 연결되었습니다",
      "toastReconnecting": "연결이 끊어졌습니다. 재연결을 시도하는 중...",
      "toastStopped": "탄막 오버레이가 중지되었습니다",
      "toastSettingsLoaded": "이전 설정을 불러왔습니다",
      "toastConnectionFailed": "서버에 연결할 수 없습니다. 설정을 확인해 주세요.",
      "errorEmptyHost": "서버 주소를 입력해 주세요",
      "errorInvalidHost": "잘못된 서버 주소입니다. 유효한 IP 또는 도메인을 입력해 주세요",
      "errorEmptyPort": "포트 번호를 입력해 주세요",
      "errorInvalidPort": "잘못된 포트입니다. 1에서 65535 사이의 숫자를 입력해 주세요",
      "exportSettings": "설정 내보내기",
      "importSettings": "설정 가져오기",
      "updateKicker": "업데이트",
      "updateAvailableShort": "업데이트",
      "updateAvailableTitle": "새 버전이 있습니다",
      "updateReadyTitle": "업데이트 설치 준비 완료",
      "updateChecking": "업데이트 확인 중…",
      "updateCheckFailed": "업데이트 확인 실패",
      "updateCheckFailedShort": "확인 실패",
      "updateUpToDate": "최신 버전입니다",
      "updateUpToDateShort": "최신",
      "updateRestartToInstall": "재시작하여 설치",
      "updateDownloadComplete": "다운로드 완료",
      "updateDownloadedToast": "업데이트가 다운로드되었습니다 — 재시작하여 설치하세요",
      "updateInstallNow": "재시작하여 설치",
      "updateRemindLater": "나중에 알림",
      "updateSkipVersion": "이 버전 건너뛰기",
      "updateSectionTitle": "업데이트",
      "updateSectionKicker": "UPDATES",
      "updateCheckNow": "지금 확인",
      "updatePrefsKicker": "UPDATE BEHAVIOR",
      "updatePrefAutoDownload": "업데이트 자동 다운로드",
      "updatePrefAutoDownloadHint": "백그라운드 다운로드 · 다음 실행에 적용",
      "updatePrefBetaChannel": "베타 채널 참여",
      "updatePrefBetaChannelHint": "새 기능 미리 체험 · 불안정할 수 있음",
      "updateChangelogKicker": "RECENT CHANGES",
      "updateChangelogFullLink": "전체 changelog →",
      "updateChangelogEmpty": "changelog 데이터 없음",
      "connSectionTitle": "연결 상태",
      "connSectionKicker": "CONNECTION",
      "firstrunLead": "댄무 서버에 연결",
      "firstrunHint": "첫 실행 시 서버 주소 설정 필요 · 설정 후 다음 실행에 자동 재연결",
      "firstrunStepServer": "SERVER",
      "firstrunStepTest": "TEST",
      "firstrunStepReady": "READY",
      "firstrunFieldLabel": "SERVER · IP / HOST",
      "firstrunFieldHelp": "wss://HOST:PORT/ws 사용 · 기본 WebSocket port 4001",
      "firstrunTestBtn": "연결 테스트",
      "firstrunRecentLabel": "RECENT",
      "firstrunRemember": "이 서버 기억 (다음 자동 연결)",
      "firstrunRememberHint": "localStorage 저장 · ⚙ 연결 → 재설정에서 초기화 가능",
      "firstrunDocsLink": "배포 문서 →",
      "firstrunSkip": "나중에 설정",
      "firstrunConfirm": "연결하고 수신 시작 →",
      "overlaySectionTitle": "Overlay",
      "overlaySectionKicker": "DISPLAY",
      "overlayCardTitle": "댄무 오버레이 표시",
      "overlayCardHint": "단축키: ⌘⇧D",
      "overlayButtonStart": "▶ Overlay 열기",
      "overlayButtonStop": "■ Overlay 닫기",
      "overlayActionClear": "⌫ 화면 지우기",
      "overlayNoteKicker": "NOTE",
      "overlayNoteBody": "댄무의 글꼴·색상·크기·투명도·속도·레이아웃·효과는 관객이 전송 시 함께 보내는 파라미터로 이 창에서는 설정하지 않습니다. 이 창은 오버레이 표시 여부·표시 디스플레이·서버 연결만 결정합니다.",
      "sectionKeysTitle": "단축키",
      "sectionKeysKicker": "SHORTCUTS",
      "sectionAboutTitle": "정보",
      "sectionAboutKicker": "ABOUT",
      "clientNavConn": "연결",
      "clientNavOverlay": "오버레이",
      "clientNavKeys": "단축키",
      "clientNavUpdate": "업데이트",
      "clientNavAbout": "정보",
      "connStatLatency": "지연",
      "connStatReconnect": "재연결",
      "connStatReconnectUnit": "회",
      "connStatUptime": "가동",
      "connBtnReconnect": "재연결",
      "connBtnEdit": "변경",
      "connBtnClose": "닫기",
      "connFlowKicker": "MESSAGE FLOW · 최근 30 초",
      "connFlowRx": "RX",
      "connFlowRate": "RATE",
      "connFlowPeak": "PEAK",
      "connEditKicker": "CONNECTION · EDIT",
      "overlayDisplayLabel": "표시 위치",
      "overlayScreenDetecting": "DISPLAY · 감지 중…",
      "overlayScreenCount": "DISPLAY · {count} 개 화면 감지"
    }
  };

const i18n = {
  currentLang: "en",

  // Exposed for backward-compatibility with tests that inspect translations directly
  translations: _resources,

  /** Translate a key with optional {var} interpolation.
   *  Respects this.currentLang so tests can do: i18n.currentLang = "zh"
   *  without needing to call setLanguage().
   *
   *  Returns the key itself when:
   *  - currentLang is not a supported locale
   *  - the key does not exist in the locale
   */
  t(key, vars) {
    if (!SUPPORTED.includes(this.currentLang)) return key;
    const dict = _resources[this.currentLang];
    if (!dict) return key;
    let text = dict[key];
    if (text === undefined) return key;
    if (vars) {
      Object.keys(vars).forEach((k) => {
        text = text.replace(new RegExp("\\{" + k + "\\}", "g"), vars[k]);
      });
    }
    return text;
  },

  setLanguage(lang) {
    if (!SUPPORTED.includes(lang)) return;
    this.currentLang = lang;
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("danmu-lang", lang);
    }
    // Update <html lang=""> so CSS :lang() picks the right CJK font
    if (typeof document !== "undefined" && document.documentElement) {
      document.documentElement.lang = lang;
    }
    this.updateUI();
  },

  /** Detect and apply the correct language (async — uses Electron IPC if available). */
  async loadLanguage() {
    const saved =
      typeof localStorage !== "undefined" && localStorage.getItem("danmu-lang");
    if (saved && SUPPORTED.includes(saved)) {
      this.currentLang = saved;
      return;
    }

    // Try Electron system locale first
    try {
      if (
        typeof window !== "undefined" &&
        window.API &&
        typeof window.API.getSystemLocale === "function"
      ) {
        const systemLocale = await window.API.getSystemLocale();
        console.log("[i18n] System locale:", systemLocale);
        const detected = this._detectLangFromLocale(systemLocale);
        if (detected) {
          this.currentLang = detected;
          return;
        }
      }
    } catch (err) {
      console.warn("[i18n] getSystemLocale failed, falling back:", err);
    }

    // Browser fallback
    const browserLang =
      typeof navigator !== "undefined"
        ? navigator.language || navigator.userLanguage
        : "";
    console.log("[i18n] Browser language:", browserLang);
    const detected = this._detectLangFromLocale(browserLang);
    if (detected) this.currentLang = detected;
  },

  _detectLangFromLocale(locale) {
    if (!locale) return null;
    if (locale.startsWith("zh")) return "zh";
    if (locale.startsWith("ja")) return "ja";
    if (locale.startsWith("ko")) return "ko";
    return null;
  },

  updateUI() {
    if (typeof document === "undefined") return;
    // Keep <html lang=""> in sync so CSS :lang() picks the right CJK font
    if (document.documentElement) {
      document.documentElement.lang = this.currentLang;
    }
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const text = this.t(key);
      if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
        el.placeholder = text;
      } else {
        el.textContent = text;
      }
    });
    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      const key = el.getAttribute("data-i18n-placeholder");
      el.placeholder = this.t(key);
    });
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = i18n;
}
