#!/usr/bin/env node
/**
 * Build script: generates server/static/js/i18n.js from locale JSON files.
 * Source of truth: server/static/locales/{lang}/translation.json
 *
 * Usage:  node scripts/build-i18n.js
 *   or:   npm run build:i18n  (from server/)
 */

const fs = require("fs");
const path = require("path");

const LOCALES_DIR = path.join(__dirname, "../static/locales");
const OUT_DIR = path.join(__dirname, "../static/js");
const OUT_FILE = path.join(OUT_DIR, "i18n.js");
const SUPPORTED = ["en", "zh", "ja", "ko"];

// Load all locale JSON files
const resources = {};
for (const lang of SUPPORTED) {
  const file = path.join(LOCALES_DIR, lang, "translation.json");
  resources[lang] = JSON.parse(fs.readFileSync(file, "utf8"));
  console.log(`  ${lang}: ${Object.keys(resources[lang]).length} keys`);
}

const output = `// AUTO-GENERATED — do NOT edit this file directly.
// Edit files in static/locales/{lang}/translation.json, then run:
//   npm run build:i18n   (from server/)

/* global i18next */
(function () {
  "use strict";

  var SUPPORTED = ["en", "zh", "ja", "ko"];

  // 2026-09-08：翻譯不再內嵌在這支檔案裡。四語全載是 670 KB，而**觀眾頁**
  // （每支手機都要下載）也載同一份。現在每個語言各自一支
  // 「i18n.<lang>.js」，由伺服器依 cookie / Accept-Language 決定送哪一支，
  // 這裡只讀 「window.__I18N_BUNDLE」。
  //
  // 換語言時若目標語言不在已載入的 bundle 裡，「_ensureLang()」 會非同步補載
  // 再重繪；同一頁第二次切回來就已經在記憶體裡了。
  var BUNDLE = window.__I18N_BUNDLE || {};

  function _toI18nextResources() {
    var out = {};
    Object.keys(BUNDLE).forEach(function (lng) {
      out[lng] = { translation: BUNDLE[lng] };
    });
    return out;
  }

  /** 確保 「lang」 的翻譯已載入。已在記憶體 → 同步 resolve。 */
  function _ensureLang(lang) {
    if (BUNDLE[lang]) return Promise.resolve(true);
    if (SUPPORTED.indexOf(lang) === -1) return Promise.resolve(false);
    return new Promise(function (resolve) {
      var el = document.createElement("script");
      // 跟本檔同目錄；用 currentScript 的路徑推導，避免寫死 /static/js/。
      el.src = _baseDir() + "i18n." + lang + ".js";
      el.onload = function () {
        BUNDLE = window.__I18N_BUNDLE || BUNDLE;
        if (BUNDLE[lang]) i18next.addResourceBundle(lang, "translation", BUNDLE[lang], true, true);
        resolve(!!BUNDLE[lang]);
      };
      el.onerror = function () { resolve(false); };
      document.head.appendChild(el);
    });
  }

  var _BASE_DIR = null;
  function _baseDir() {
    if (_BASE_DIR) return _BASE_DIR;
    var cur = document.currentScript;
    var src = (cur && cur.src) || "";
    _BASE_DIR = src ? src.slice(0, src.lastIndexOf("/") + 1) : "/static/js/";
    return _BASE_DIR;
  }
  _baseDir();   // 趁 currentScript 還有效時先算好

  function detectLang() {
    var saved = localStorage.getItem("danmu-server-lang");
    if (saved && SUPPORTED.indexOf(saved) !== -1) return saved;
    var bl = navigator.language.toLowerCase();
    if (bl.startsWith("zh")) return "zh";
    if (bl.startsWith("ja")) return "ja";
    if (bl.startsWith("ko")) return "ko";
    return "en";
  }

  // 語言碼 → BCP47。單一個 zh 是不夠的：它沒說是正體還是簡體，
  // 螢幕閱讀器與 CJK 字型選擇都吃這個標籤（設計稿 17）。
  var HTML_LANG = { zh: "zh-Hant", en: "en", ja: "ja", ko: "ko" };

  window.ServerI18n = {
    currentLang: "zh",

    init: function () {
      var wanted = detectLang();
      var loaded = Object.keys(BUNDLE);
      // 伺服器送來的那一支未必等於 detectLang()（例如 localStorage 與 cookie
      // 不同步）。先用手上有的把畫面畫出來，再非同步補上想要的那個語言。
      this.currentLang = BUNDLE[wanted] ? wanted : (loaded[0] || "en");

      i18next.init({
        lng: this.currentLang,
        fallbackLng: loaded.indexOf("en") !== -1 ? "en" : this.currentLang,
        resources: _toI18nextResources(),
        interpolation: {
          prefix: "{",
          suffix: "}",
          escapeValue: false,
          // Preserve placeholder when variable is not passed,
          // so existing .replace("{key}", val) call-sites keep working.
          missingInterpolationHandler: function (_text, match) {
            return "{" + match[1] + "}";
          },
        },
      });

      this._syncHtmlLang();
      this.updateUI();

      if (wanted !== this.currentLang) {
        var self = this;
        _ensureLang(wanted).then(function (ok) {
          if (ok) self.setLanguage(wanted);
        });
      }
    },

    /** Translate a key, optionally with interpolation vars.
     *  New code:      ServerI18n.t("overlayConnected", { n: count })
     *  Legacy code:   ServerI18n.t("overlayConnected").replace("{n}", count)
     *  Both work.
     */
    t: function (key, vars) {
      return i18next.t(key, vars);
    },

    /**
     * BCP47 tag for Date#toLocale*String，跟隨 UI 語言。
     * 取代散落各模組的硬編 "zh-TW"（design audit 遺留統一，2026-08-09）。
     */
    dateLocale: function () {
      return { zh: "zh-TW", en: "en-US", ja: "ja-JP", ko: "ko-KR" }[this.currentLang];
    },

    setLanguage: function (lang) {
      if (SUPPORTED.indexOf(lang) === -1) return;
      var self = this;
      // cookie 是給**伺服器**看的：下一次載入才知道該送哪一支 bundle。
      // localStorage 仍然是前端的真相來源（cookie 可能被清、也可能被代理剝掉）。
      try { localStorage.setItem("danmu-server-lang", lang); } catch (_) {}
      try {
        document.cookie =
          "danmu-server-lang=" + lang + ";path=/;max-age=31536000;samesite=Lax";
      } catch (_) {}
      _ensureLang(lang).then(function () {
        self.currentLang = lang;
        i18next.changeLanguage(lang);
        self._syncHtmlLang();
        self.updateUI();
      });
    },

    /** <html lang> 跟隨介面語言（設計稿 17）。CSS 的 :lang() 靠它挑 CJK
     *  字型，螢幕閱讀器靠它挑發音。**每一頁都要**——原本 admin 與 overlay
     *  的靜態標記寫死 lang="en"，稿上直接把這件事標成 bug。 */
    _syncHtmlLang: function () {
      if (!document.documentElement) return;
      document.documentElement.lang = HTML_LANG[this.currentLang] || this.currentLang;
    },

    updateUI: function () {
      document.querySelectorAll("[data-i18n]").forEach(function (el) {
        var key = el.getAttribute("data-i18n");
        var text = i18next.t(key);
        if (text !== key) el.textContent = text;
      });
      document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
        var key = el.getAttribute("data-i18n-placeholder");
        var text = i18next.t(key);
        if (text !== key) el.placeholder = text;
      });
      document.querySelectorAll("[data-i18n-title]").forEach(function (el) {
        var key = el.getAttribute("data-i18n-title");
        var text = i18next.t(key);
        if (text !== key) el.title = text;
      });
      document.querySelectorAll("[data-i18n-aria]").forEach(function (el) {
        var key = el.getAttribute("data-i18n-aria");
        var text = i18next.t(key);
        if (text !== key) el.setAttribute("aria-label", text);
      });
      this.bindLanguageSelector();
      if (window._adminNavigateTo) window._adminNavigateTo();
    },

    bindLanguageSelector: function () {
      var self = this;
      var sel = document.getElementById("server-lang-select");
      if (!sel) return;
      sel.value = this.currentLang;
      if (sel.dataset.i18nBound === "true") return;
      sel.addEventListener("change", function (e) {
        self.setLanguage(e.target.value);
      });
      sel.dataset.i18nBound = "true";
    },
  };
})();
`;

fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`\nWrote ${OUT_FILE} (${(output.length / 1024).toFixed(1)} KB) — runtime only`);

// 每個語言一支。伺服器依 cookie / Accept-Language 決定 <script> 指向哪一支，
// 前端要別的語言時由 runtime 自己補載。
for (const lang of SUPPORTED) {
  const file = path.join(OUT_DIR, `i18n.${lang}.js`);
  const body = `// AUTO-GENERATED — do NOT edit. Source: static/locales/${lang}/translation.json
window.__I18N_BUNDLE = window.__I18N_BUNDLE || {};
window.__I18N_BUNDLE[${JSON.stringify(lang)}] = ${JSON.stringify(resources[lang])};
`;
  fs.writeFileSync(file, body, "utf8");
  console.log(`  ${path.basename(file)}  ${(body.length / 1024).toFixed(1)} KB`);
}
