#!/usr/bin/env node
/**
 * Build script: generates server/static/js/i18n.js from locale JSON files.
 * Source of truth: server/static/locales/{lang}/translation.json
 *
 * Usage:  node scripts/build-i18n.js
 *   or:   npm run build:i18n  (from server/)
 */

const fs = require("fs");
const path = require("path");

const LOCALES_DIR = path.join(__dirname, "../static/locales");
const OUT_FILE = path.join(__dirname, "../static/js/i18n.js");
const SUPPORTED = ["en", "zh", "ja", "ko"];

// Load all locale JSON files
const resources = {};
for (const lang of SUPPORTED) {
  const file = path.join(LOCALES_DIR, lang, "translation.json");
  resources[lang] = JSON.parse(fs.readFileSync(file, "utf8"));
  console.log(`  ${lang}: ${Object.keys(resources[lang]).length} keys`);
}

const resourcesJson = JSON.stringify(resources, null, 2);

const output = `// AUTO-GENERATED — do NOT edit this file directly.
// Edit files in static/locales/{lang}/translation.json, then run:
//   npm run build:i18n   (from server/)

/* global i18next */
(function () {
  "use strict";

  var SUPPORTED = ["en", "zh", "ja", "ko"];

  var resources = ${resourcesJson.replace(/^/gm, "  ").trimStart()};

  // Wrap each locale into { translation: {...} } as i18next expects
  var i18nextResources = {};
  SUPPORTED.forEach(function (lng) {
    i18nextResources[lng] = { translation: resources[lng] };
  });

  function detectLang() {
    var saved = localStorage.getItem("danmu-server-lang");
    if (saved && SUPPORTED.indexOf(saved) !== -1) return saved;
    var bl = navigator.language.toLowerCase();
    if (bl.startsWith("zh")) return "zh";
    if (bl.startsWith("ja")) return "ja";
    if (bl.startsWith("ko")) return "ko";
    return "en";
  }

  window.ServerI18n = {
    currentLang: "zh",

    init: function () {
      this.currentLang = detectLang();

      i18next.init({
        lng: this.currentLang,
        fallbackLng: "en",
        resources: i18nextResources,
        interpolation: {
          prefix: "{",
          suffix: "}",
          escapeValue: false,
          // Preserve placeholder when variable is not passed,
          // so existing .replace("{key}", val) call-sites keep working.
          missingInterpolationHandler: function (_text, match) {
            return "{" + match[1] + "}";
          },
        },
      });

      // Set <html lang=""> so CSS :lang() can apply the right CJK font
      if (document.documentElement) {
        document.documentElement.lang = this.currentLang;
      }

      this.updateUI();
    },

    /** Translate a key, optionally with interpolation vars.
     *  New code:      ServerI18n.t("overlayConnected", { n: count })
     *  Legacy code:   ServerI18n.t("overlayConnected").replace("{n}", count)
     *  Both work.
     */
    t: function (key, vars) {
      return i18next.t(key, vars);
    },

    setLanguage: function (lang) {
      if (SUPPORTED.indexOf(lang) === -1) return;
      this.currentLang = lang;
      localStorage.setItem("danmu-server-lang", lang);
      // changeLanguage is async but resources are already loaded — resolves instantly
      i18next.changeLanguage(lang);
      // Update <html lang=""> so CSS :lang() picks the right CJK font
      if (document.documentElement) {
        document.documentElement.lang = lang;
      }
      this.updateUI();
    },

    updateUI: function () {
      document.querySelectorAll("[data-i18n]").forEach(function (el) {
        var key = el.getAttribute("data-i18n");
        var text = i18next.t(key);
        if (text !== key) el.textContent = text;
      });
      document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
        var key = el.getAttribute("data-i18n-placeholder");
        var text = i18next.t(key);
        if (text !== key) el.placeholder = text;
      });
      document.querySelectorAll("[data-i18n-title]").forEach(function (el) {
        var key = el.getAttribute("data-i18n-title");
        var text = i18next.t(key);
        if (text !== key) el.title = text;
      });
      this.bindLanguageSelector();
    },

    bindLanguageSelector: function () {
      var self = this;
      var sel = document.getElementById("server-lang-select");
      if (!sel) return;
      sel.value = this.currentLang;
      if (sel.dataset.i18nBound === "true") return;
      sel.addEventListener("change", function (e) {
        self.setLanguage(e.target.value);
      });
      sel.dataset.i18nBound = "true";
    },
  };
})();
`;

fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`\nWrote ${OUT_FILE} (${(output.length / 1024).toFixed(1)} KB)`);
