#!/usr/bin/env node
/**
 * Build script: generates danmu-desktop/i18n.js from locale JSON files.
 * Source of truth: danmu-desktop/locales/{lang}/translation.json
 *
 * Usage:  node scripts/build-i18n.js
 *   or:   npm run build:i18n  (from danmu-desktop/)
 */

const fs = require("fs");
const path = require("path");

const LOCALES_DIR = path.join(__dirname, "../locales");
const OUT_FILE = path.join(__dirname, "../i18n.js");
const SUPPORTED = ["en", "zh", "ja", "ko"];

// Load all locale JSON files
const resources = {};
for (const lang of SUPPORTED) {
  const file = path.join(LOCALES_DIR, lang, "translation.json");
  resources[lang] = JSON.parse(fs.readFileSync(file, "utf8"));

  // Validate: all locales must have the same keys as en
  if (lang !== "en") {
    const enKeys = Object.keys(resources.en);
    const langKeys = Object.keys(resources[lang]);
    const missing = enKeys.filter((k) => !langKeys.includes(k));
    const extra = langKeys.filter((k) => !enKeys.includes(k));
    if (missing.length) console.warn(`  [warn] ${lang} missing keys: ${missing.join(", ")}`);
    if (extra.length) console.warn(`  [warn] ${lang} extra keys: ${extra.join(", ")}`);
  }

  console.log(`  ${lang}: ${Object.keys(resources[lang]).length} keys`);
}

const resourcesJson = JSON.stringify(resources, null, 2);

const output = `// AUTO-GENERATED — do NOT edit this file directly.
// Edit files in locales/{lang}/translation.json, then run:
//   npm run build:i18n   (from danmu-desktop/)

/* eslint-disable */

const SUPPORTED = ["en", "zh", "ja", "ko"];

const _resources = ${resourcesJson.replace(/^/gm, "  ").trimStart()};

const i18n = {
  currentLang: "en",

  // Exposed for backward-compatibility with tests that inspect translations directly
  translations: _resources,

  /** Translate a key with optional {var} interpolation.
   *  Respects this.currentLang so tests can do: i18n.currentLang = "zh"
   *  without needing to call setLanguage().
   *
   *  Returns the key itself when:
   *  - currentLang is not a supported locale
   *  - the key does not exist in the locale
   */
  t(key, vars) {
    if (!SUPPORTED.includes(this.currentLang)) return key;
    const dict = _resources[this.currentLang];
    if (!dict) return key;
    let text = dict[key];
    if (text === undefined) return key;
    if (vars) {
      Object.keys(vars).forEach((k) => {
        text = text.replace(new RegExp("\\\\{" + k + "\\\\}", "g"), vars[k]);
      });
    }
    return text;
  },

  setLanguage(lang) {
    if (!SUPPORTED.includes(lang)) return;
    this.currentLang = lang;
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("danmu-lang", lang);
    }
    this.updateUI();
  },

  /** Detect and apply the correct language (async — uses Electron IPC if available). */
  async loadLanguage() {
    const saved =
      typeof localStorage !== "undefined" && localStorage.getItem("danmu-lang");
    if (saved && SUPPORTED.includes(saved)) {
      this.currentLang = saved;
      return;
    }

    // Try Electron system locale first
    try {
      if (
        typeof window !== "undefined" &&
        window.API &&
        typeof window.API.getSystemLocale === "function"
      ) {
        const systemLocale = await window.API.getSystemLocale();
        console.log("[i18n] System locale:", systemLocale);
        const detected = this._detectLangFromLocale(systemLocale);
        if (detected) {
          this.currentLang = detected;
          return;
        }
      }
    } catch (err) {
      console.warn("[i18n] getSystemLocale failed, falling back:", err);
    }

    // Browser fallback
    const browserLang =
      typeof navigator !== "undefined"
        ? navigator.language || navigator.userLanguage
        : "";
    console.log("[i18n] Browser language:", browserLang);
    const detected = this._detectLangFromLocale(browserLang);
    if (detected) this.currentLang = detected;
  },

  _detectLangFromLocale(locale) {
    if (!locale) return null;
    if (locale.startsWith("zh")) return "zh";
    if (locale.startsWith("ja")) return "ja";
    if (locale.startsWith("ko")) return "ko";
    return null;
  },

  updateUI() {
    if (typeof document === "undefined") return;
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const text = this.t(key);
      if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
        el.placeholder = text;
      } else {
        el.textContent = text;
      }
    });
    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      const key = el.getAttribute("data-i18n-placeholder");
      el.placeholder = this.t(key);
    });
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = i18n;
}
`;

fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`\nWrote ${OUT_FILE} (${(output.length / 1024).toFixed(1)} KB)`);
